---
- name: Check NFS utilities package installation
  package: 
    name: nfs-utils 
    state: present

- name: Ensure rpcbind is running as configured
  service:
    name: rpcbind
    state: started
    enabled: true

- name: Ensure directories to export exist
  file:  
    path: "{{ item.path }}"
    state: directory
  with_items: "{{ nfs_exports }}"

- name: Generate exports file
  template:
    src: etc/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: reload nfs

- name: Ensure nfs server daemon is running
  service: 
    name: "nfs-server" 
    state: "started" 
    enabled: yes
  when: nfs_exports|length