---
# tasks file for common-linux
#
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: False

- name: Install Required Packages
  yum:
    name: "{{ common_packages }}"
    state: present

- name: Set timezone to Europe/Rome
  community.general.timezone:
    name: Europe/Rome
